🔧 add command sonarqube in mix.exs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -51,20 +51,24 @@ jobs:
           mix local.hex --force || echo "Hex not installed correctly"
           mix local.rebar --force || echo "Rebar not installed correctly"
 
+      - name: Run Credo analysis
+        run: |
+          # Change to your Elixir app directory
+          cd apiTimemanager
+
+          # Install project dependencies
+          mix do deps.get, deps.compile || echo "Dependencies not installed correctly"
+
+          # Run Credo for static code analysis and save the report in a file
+          mix credo --format=oneline --strict > credo_analysis.txt || echo "Credo analysis failed"
+
       - name: Run Elixir analysis on apiTimemanager
         run: |
           # Change to your Elixir app directory
           cd apiTimemanager
 
-          #Install Credo
-          mix archive.install --yes hex credo || echo "Credo not installed correctly"
-          echo "Credo installed"
-
           # Install project dependencies
           mix do deps.get, deps.compile || echo "Dependencies not installed correctly"
-
-          # Run Credo for static code analysis
-          mix credo --strict || echo "Credo analysis failed"
 
           # Run SonarQube analysis for Elixir
           echo "Running SonarQube analysis for Elixir..."
